### ISSUE TITLE
utf-8 decode error

### ISSUE THREAD

**Issue by SeverinoDaDalt** [SeverinoDaDalt/language_learning_assistant#2]
Error:
```
Traceback (most recent call last):
  File "/home/severino/Workspace/projects/language_learning_assistant/main.py", line 123, in <module>
    main()
  File "/home/severino/Workspace/projects/language_learning_assistant/main.py", line 119, in main
    session.run()
  File "/home/severino/Workspace/projects/language_learning_assistant/main.py", line 98, in run
    new_interactions = exhaustive_training(self.dictionary.words)
  File "/home/severino/Workspace/projects/language_learning_assistant/training.py", line 62, in exhaustive_training
    interaction, result = ask_spanish_translation(word)
  File "/home/severino/Workspace/projects/language_learning_assistant/training.py", line 23, in ask_spanish_translation
    response = keyboard_adapter(ask_user(prompt))
  File "/home/severino/Workspace/projects/language_learning_assistant/utils.py", line 33, in ask_user
    response = input(f"{USERNAME}: ").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 2: invalid continuation byte
```
Something like a `try-except` should work:

**Comment by SeverinoDaDalt** [comment]
Just implemented function `read_from_user`. Problem should be solved.
